keep_playing/keep_playing/urls.py
from django.urls import include, path
from . import views

from django.contrib import admin

#the two lines below are to allow the application to access media files 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('sheetreader/', include('sheetreader.urls')),
]


#adds media files to urlpatterns (giving the website access to them)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

keep_playing/sheetreader/urls.py
from django.urls import path

from . import views # imports views.py from this directory

app_name = 'sheetreader'

urlpatterns = [
	path('', views.index, name='index'),
	path('sheet/<int:pk>/view/', views.sheetReader, name='sheetReader'),
	path('sheet/create/', views.newSheet, name='newSheet'),
    path('sheet/<int:pk>/update/', views.updateSheet, name='updateSheet'),
    path('delete/', views.deleteSheets, name='deleteSheets'),
	path('readGesture', views.readGesture, name="readGesture"),
]

keep_playing/sheetreader/models.py
from django.db import models
from django.forms import ModelForm
# Create your models here.

class Sheet(models.Model):
	sheet_name = models.CharField(max_length=50)
	sheet_file = models.FileField(upload_to='files')
	
	def __str__(self):
		return self.sheet_name

class SheetForm(ModelForm):
	class Meta(object):
		model = Sheet 
		fields = '__all__'

keep_playing/keep_playing/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
	return HttpResponseRedirect(reverse('sheetreader:index'))

keep_playing/sheetreader/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import *

from django.http import HttpResponse
from django.contrib.staticfiles.templatetags.staticfiles import static
import numpy as np
import cv2
from collections import namedtuple
import time
from msvcrt import getch

def index(request):
	sheet_data = Sheet.objects.all()
	return render(request, 'sheetreader/home.html', {'sheet_data': sheet_data})

def sheetReader(request, pk):
	sheet = get_object_or_404(Sheet, pk=pk)
	return render(request, 'sheetreader/reader.html', {'sheet': sheet})

def newSheet(request):
	form = SheetForm(request.POST or None, request.FILES or None)
	if request.method == 'POST':
		if form.is_valid():
			form.save() # saves the object that was just created
			return HttpResponseRedirect(reverse('sheetreader:index')) # once completed, return to home
	return render(request, "sheetreader/sheet_form.html", {'form': form})

def updateSheet(request, pk=None):
	instance = get_object_or_404(Sheet, pk=pk)
	form = SheetForm(request.POST or None, request.FILES or None, instance=instance)
	# if form submission was successful
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('sheetreader:index'))
	return render(request, "sheetreader/sheet_form.html", {'form': form})

def deleteSheets(request):
	items = request.POST.getlist('items') # receives a list of the items through a request.POST
	Sheet.objects.filter(id__in=request.POST.getlist('items')).delete()
	return HttpResponseRedirect(reverse('sheetreader:index'))

#Determines if current list contains a guesture
def checkGuesture(pointsTracking):
    if pointsTracking[0].Pose != "Front":
        return "Null"
    
    frontPreDetected = False
    frontPreCount = 0
    frontPreX = 0

    leftDetected = False
    leftCount = 0
    leftX = 0

    rightDetected = False
    rightCount = 0
    rightX = 0

    frontPostDetected = False
    frontPostCount = 0
    frontPostX = 0

    for point in pointsTracking:
        if point.Pose == "Front":
            if not leftDetected  and not rightDetected :
                frontPreCount += 1
                frontPreX += point.X
                if frontPreCount > 3:
                    frontPreDetected = True
            else:
                frontPostCount += 1
                frontPostX += point.X
                if frontPostCount > 3:
                    frontPostDetected = True
        elif point.Pose == "Left" and frontPreDetected:
            leftCount += 1
            leftX += point.X    
            if leftCount > 3:
                leftDetected = True
        elif point.Pose == "Right" and frontPreDetected:
            rightCount += 1
            rightX += point.X    
            if rightCount > 3:
                rightDetected = True

    if frontPreDetected and frontPostDetected:
        frontPreXAvg = frontPreX / frontPreCount
        frontPostAvg = frontPostX / frontPostCount
        if leftDetected:
            leftXAvg = leftX / leftCount
            if leftXAvg < frontPreXAvg and leftXAvg < frontPostAvg:
                #print("Guesture Left Detected")
                return "Left Detected"
        elif rightDetected:
            rightXAvg = rightX / rightCount
            if rightXAvg > frontPreXAvg and rightXAvg > frontPostAvg:
                #print("Guesture Right Detected")
                return "Right Detected"
    return ""

def trimList(pointsTracking):
    lastTime = pointsTracking[len(pointsTracking) - 1].Time
    trimmed = False
    while not trimmed:
        if (lastTime - pointsTracking[0].Time) > 3:
            pointsTracking.pop(0)
        else: 
            trimmed = True
    return pointsTracking

cap = cv2.VideoCapture(0)
defaultURL = static('haarcascade_frontalface_default.xml')
profileURL = static('haarcascade_profileface.xml')
face_cascade = cv2.CascadeClassifier(defaultURL)
face_cascade_profile = cv2.CascadeClassifier(profileURL)

#Point data structure - tracks position & pose
Point = namedtuple("Point", "X Y Size Pose Time")

#Initiailze camera & classifiers

def readGesture(placeholder):

	#Chronological list of tracking points
	pointsTracking = []
	startTime = time.clock
	while(True):
		#Reads frame from camera & flips to act like mirror
		ret, frame = cap.read()   

		#Checks if frame was read
		if ret:
			frameFlipped = cv2.flip(frame, 1)
			#Converts to greyscale (Quicker processing) & flips to act like a mirror
			gray = cv2.cvtColor(frameFlipped, cv2.COLOR_BGR2GRAY)

			#Detect frontal face
			faces = face_cascade.detectMultiScale(gray, 1.3, 5)
			
			largestFace = Point(0,0,0,"", 0)
			if len(faces) > 0:
				for (x, y, w, h) in faces:
					if(w * h > largestFace.Size):
						largestFace = Point(x, y, w * h, "Front", time.clock())
					cv2.rectangle(frameFlipped, (x,y), (x+w, y+h), (255, 0, 0), 2)
			else:
				#If no frontal face detected, check for profiles of faces
				faces_profile = face_cascade_profile.detectMultiScale(gray, 1.3, 5)

				if len(faces_profile) > 0:
					for (x, y, w, h) in faces_profile:
						if(w * h > largestFace.Size):
							largestFace = Point(x, y, w * h, "Left", time.clock())
						cv2.rectangle(frameFlipped, (x,y), (x+w, y+h), (0, 0, 255), 2)
				else:
					#Checks for flipped face profiles (classifier only check one orientation)
					grayFlipped = cv2.flip(gray, 1)
					faces_profile_flipped = face_cascade_profile.detectMultiScale(grayFlipped, 1.3, 5)
					width, height = grayFlipped.shape[:2]

					for (x, y, w, h) in faces_profile_flipped:
						if(w * h > largestFace.Size):
							largestFace = Point(width - x, y, w * h, "Right", time.clock())
						cv2.rectangle(frameFlipped, (width - x,y), (width - x+w, y+h), (0, 0, 255), 2)
			if largestFace.Pose == "":
				largestFace = Point(0, 0, 0, "", time.clock())

			pointsTracking.append(largestFace)
			pointsTracking = trimList(pointsTracking)

			guestureDetected = checkGuesture(pointsTracking)  
			if guestureDetected == "Left Detected":
				return HttpResponse("Left")
			elif guestureDetected == "Right Detected":
				return HttpResponse("Right")
			
			#if space is pressed
			if key == 32:
				return HttpResponse("")
				cap.release
				cv2.destroyAllWindows

			cv2.imshow('Frame', frameFlipped)
			cv2.waitKey(30)

	cap.release
	cv2.destroyAllWindows

keep_playing/sheetreader/templates/sheetreader/base.html
{% load static %} 
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<title> Keep-Playing </title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	

	<style type="text/css">
		@import url(https://fonts.googleapis.com/css?family=Raleway);

		html, body {
		  font-family: Raleway, sans-serif;  
		}

	</style>
	
</head>
<body>
			<nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="height: 58px;">
				<!-- Brand -->
				<a class="navbar-brand" href="{% url 'sheetreader:index' %}" id="navbarName"> Keep-Playing by Naitao Cui and Derek Liu </a>

				<!-- Links -->
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'sheetreader:newSheet' %}"> Upload another PDF </a>
					</li>
				</ul>
				<ul class="navbar-nav">
					<li class="nav-item right">
						<a class="nav-link disabled" href="#">Help</a>
					</li>
				</ul>
			</nav>

	<div id="content">
		{% block content %}{% endblock %}
	</div>

</body>
</html>

keep_playing/sheetreader/templates/sheetreader/home.html
{% extends "sheetreader/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
{% block content %}
<head>
	<title></title>
</head>
<body>

	<button class="button btn btn-primary" data-href="{% url 'sheetreader:newSheet' %}" style="float: left;"> Add New Sheet</button>

	<!-- this form wraps the entire table as it tracks which rows have been selected to be deleted -->
	<form action="{% url 'sheetreader:deleteSheets' %}" method="POST"> 
		{% csrf_token %}
		<button type="submit" class="btn btn-primary" name="delete" style="float: right;"> Delete Selected Sheets </button> 

		<table class="table table-bordered table-hover table-sm">
			<thead class="thead-light">
				<tr>
					<th scope="col"> Sheet </th>
					<th scope="col"> Start Reading </th>
					<th scope="col"> Edit </th>
					<th scope="col"> Delete </th>			
				</tr>
			</thead>
			<tbody>
				{% for sheet in sheet_data %}					
					<tr>
						<td scope="col" class="details"> {{ sheet }} </td>  
						<td><button type="button" class="btn btn-primary btn-sm" data-href="{% url 'sheetreader:sheetReader' sheet.id %}"> Sheet Reader </button></td>	
						<td><button type="button" class="btn btn-primary btn-sm" data-href="{% url 'sheetreader:updateSheet' sheet.id %}"> Edit Me </button></td>					
						<td scope="col" class="deleteCol"> <input name="items" class="checkboxes" type="checkbox" value="{{ sheet.pk }}"> </td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</form>

	<script type="text/javascript">
		
		$(document).ready(function($) {
	    	$(".btn").click(function() {
	       		window.document.location = $(this).data("href");		       			       		
	    	});
		});

	</script>

</body>
{% endblock %}
</html>

keep_playing/sheetreader/templates/sheetreader/reader.html
{% extends "sheetreader/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
{% block content %}
<head>
	<script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
	<style type="text/css">
		#the-canvas{
			display: block;
			margin: auto;
			width: 70%;
		}
	</style>
</head>
<body>

<div class="row container">
	<button id="prev" class="btn btn-primary">Previous</button>
	<button id="next" class="btn btn-primary">Next</button>
	&nbsp; &nbsp;
	<span>Page: <span id="page_num"></span> / <span id="page_count"></span></span>
	&nbsp; &nbsp;
	<button class="test btn btn-primary" onclick="scrollDown()"><strong>Down</strong></button>
  <button class="btn btn-primary" onclick="scrollup()"><strong>Up</strong></button>
  <br>
  <button class="btn btn-primary" onclick="startDetection()"><strong>Start Detection</strong></button>
</div>

<canvas id="the-canvas"></canvas>

<script type="text/javascript">

var x = 150;

$(document).ready(function() {
    $(".test").click(function(event){
        $('html, body').animate({scrollTop: x+'px'}, 800);
        x += 150;
    });
});

	// If absolute URL from the remote server is provided, configure the CORS
// header on that server.
var url = '/media/' + '{{sheet.sheet_file}}';

// Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';

var pdfDoc = null,
    pageNum = 1,
    pageRendering = false,
    pageNumPending = null,
    scale = 2,
    canvas = document.getElementById('the-canvas'),
    ctx = canvas.getContext('2d');

/**
 * Get page info from document, resize canvas accordingly, and render page.
 * @param num Page number.
 */
function renderPage(num) {
  pageRendering = true;
  // Using promise to fetch the page
  pdfDoc.getPage(num).then(function(page) {
    var viewport = page.getViewport(scale);
    canvas.height = viewport.height;
    canvas.width = viewport.width;

    // Render PDF page into canvas context
    var renderContext = {
      canvasContext: ctx,
      viewport: viewport
    };
    var renderTask = page.render(renderContext);

    // Wait for rendering to finish
    renderTask.promise.then(function() {
      pageRendering = false;
      if (pageNumPending !== null) {
        // New page rendering is pending
        renderPage(pageNumPending);
        pageNumPending = null;
      }
    });
  });

  // Update page counters
  document.getElementById('page_num').textContent = num;
}

/**
 * If another page rendering in progress, waits until the rendering is
 * finised. Otherwise, executes rendering immediately.
 */
function queueRenderPage(num) {
  if (pageRendering) {
    pageNumPending = num;
  } else {
    renderPage(num);
  }
}

/**
 * Displays previous page.
 */
function onPrevPage() {
  if (pageNum <= 1) {
    return;
  }
  pageNum--;
  queueRenderPage(pageNum);
}
document.getElementById('prev').addEventListener('click', onPrevPage);

/**
 * Displays next page.
 */
function onNextPage() {
  if (pageNum >= pdfDoc.numPages) {
    return;
  }
  pageNum++;
  queueRenderPage(pageNum);
}
document.getElementById('next').addEventListener('click', onNextPage);

/**
 * Asynchronously downloads PDF.
 */
pdfjsLib.getDocument(url).then(function(pdfDoc_) {
  pdfDoc = pdfDoc_;
  document.getElementById('page_count').textContent = pdfDoc.numPages;

  // Initial/first page rendering
  renderPage(pageNum);
});

function startDetection()
{
  $.get("{% url 'sheetreader:readGesture'%}", function(data) {detected(data)});
}

function detected(data)
{
  if(data == "Left")
  {
    scrollup();
    startDetection();
  }
  else if (data == "Right")
  {
    scrollDown();
    startDetection();
  }
}

</script>

</body>
{% endblock %}
</html>

keep_playing/sheetreader/templates/sheetreader/reader2.html
{% extends "sheetreader/base.html" %}
{% load static %}
<!DOCTYPE html>
<html>
{% block content %}
<head>
    <script type="text/javascript" src="{% static 'sheetreader/dist/jeelizFaceFilter.js' %}"></script>
    <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
    <style type="text/css">
        #the-canvas{
            display: block;
            margin: auto;
            width: 70%;
        }
        ::-webkit-scrollbar {
            display: none;
        }

    </style>

</head>
<body>
    <canvas width="700" height="700" id='jeeFaceFilterCanvas' hidden=""></canvas>
    <div class="row container">
    <button id="prev" class="btn btn-primary" hidden=""></button>
    <button id="next" class="btn btn-primary" hidden=""></button>
    <button id="scroll_up" class="btn btn-primary" hidden=""></button>
    <button id="scroll_down" class="btn btn-primary" hidden=""></button>

    &nbsp; &nbsp;
    <button class="btn btn-primary" onclick="calibrate()"> Calibrate </button>
    <span>Page: <span id="page_num"></span> / <span id="page_count"></span></span>
</div>

<canvas id="the-canvas"></canvas>
</body>
<script type="text/javascript">
// script to scroll up and down

var x = 150;

// $(document).ready(function() {
//     $("#scroll_down").click(function(event){
//         $('html, body').animate({scrollTop: x+'px'}, 800);
//         x += 150;
//     });
//     $("#scroll_up").click(function(event){
//         $('html, body').animate({scrollTop: x+'px'}, 800);
//         x -= 150;
//     });
// });

function scroll_up(){
    $('html, body').animate({scrollTop: x+'px'}, 400);
    x += 150;
}

function scroll_down(){
    $('html, body').animate({scrollTop: x+'px'}, 400);
    x -= 150;
}

// script to change pages

    var newAvg = true;
    var count = 0;
    var total_hori_angle = 0;
    var total_vert_angle = 0;
    var avg_hori_angle = 0;
    var avg_vert_angle = 0;
    var current_hori_angle = 0;
    var current_vert_angle = 0;
    var lastCall = new Date();
    var difference = 0;

    function calibrate(){
        // reset values
        count = 0;
        total_hori_angle = 0; 
        total_vert_angle = 0;
        newAvg = true;
    }

    JEEFACEFILTERAPI.init({
        canvasId: 'jeeFaceFilterCanvas',
        NNCpath: '{% static "sheetreader/dist/" %}', //root of NNC.json file
        callbackReady: function(errCode, spec){
            if (errCode){
                console.log('AN ERROR HAPPENS. ERROR CODE =', errCode);
                return;
            }
            console.log('INFO : JEEFACEFILTERAPI IS READY');
        }, 
        //called at each render iteration (drawing loop)
        callbackTrack: function(detectState){
            // function calibrate: tell user to sit in neutral position and record an average of values
            // 
            if(newAvg && count < 100){
                // calc sum of horizontal angles
                total_hori_angle += detectState.ry * 180 / Math.PI; 
                // calc sum of vertical angles
                total_vert_angle += detectState.rx * 180 / Math.PI;
                count++;
            }

            if(newAvg && count == 99){
                avg_hori_angle = total_hori_angle/100;
                avg_vert_angle = total_vert_angle/100;
                newAvg = false;
                // console.log(avg_vert_angle)
                // console.log(avg_hori_angle)
            }

            current_vert_angle = detectState.rx * 180 / Math.PI;
            current_hori_angle = detectState.ry * 180 / Math.PI;

            difference = new Date() - lastCall;

            if(difference > 2000 && !newAvg){
                console.log('hey')
                if((current_hori_angle - avg_hori_angle) > 30){
                    // do something
                    console.log("Left Head Turn")
                    $('#prev').click().delay(2000);
                    lastCall = new Date();
                }
                if((current_hori_angle - avg_hori_angle < -30)){
                    // do something
                    console.log("Right Head Turn")
                    $('#next').click().delay(2000);
                    lastCall = new Date();
                }
                if((current_vert_angle - avg_vert_angle > 8)){
                    // do something
                    console.log("Tilted Head Down")
                    scroll_down();
                    lastCall = new Date();
                }
                if((current_vert_angle - avg_vert_angle < -10 )){
                    // do something
                    console.log("Lifted Head Up")
                    scroll_up();
                    lastCall = new Date();
                }
            }

        } 
    });


</script>


<!-- script for PDF.js -->
<script type="text/javascript">

    // If absolute URL from the remote server is provided, configure the CORS
// header on that server.
var url = '/media/' + '{{sheet.sheet_file}}';

// Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';

var pdfDoc = null,
    pageNum = 1,
    pageRendering = false,
    pageNumPending = null,
    scale = 2,
    canvas = document.getElementById('the-canvas'),
    ctx = canvas.getContext('2d');

/**
 * Get page info from document, resize canvas accordingly, and render page.
 * @param num Page number.
 */
function renderPage(num) {
  pageRendering = true;
  // Using promise to fetch the page
  pdfDoc.getPage(num).then(function(page) {
    var viewport = page.getViewport(scale);
    canvas.height = viewport.height;
    canvas.width = viewport.width;

    // Render PDF page into canvas context
    var renderContext = {
      canvasContext: ctx,
      viewport: viewport
    };
    var renderTask = page.render(renderContext);

    // Wait for rendering to finish
    renderTask.promise.then(function() {
      pageRendering = false;
      if (pageNumPending !== null) {
        // New page rendering is pending
        renderPage(pageNumPending);
        pageNumPending = null;
      }
    });
  });

  // Update page counters
  document.getElementById('page_num').textContent = num;
}

/**
 * If another page rendering in progress, waits until the rendering is
 * finised. Otherwise, executes rendering immediately.
 */
function queueRenderPage(num) {
  if (pageRendering) {
    pageNumPending = num;
  } else {
    renderPage(num);
  }
}

/**
 * Displays previous page.
 */
function onPrevPage() {
  if (pageNum <= 1) {
    return;
  }
  pageNum--;
  queueRenderPage(pageNum);
}
document.getElementById('prev').addEventListener('click', onPrevPage);

/**
 * Displays next page.
 */
function onNextPage() {
  if (pageNum >= pdfDoc.numPages) {
    return;
  }
  pageNum++;
  queueRenderPage(pageNum);
}
document.getElementById('next').addEventListener('click', onNextPage);

/**
 * Asynchronously downloads PDF.
 */
pdfjsLib.getDocument(url).then(function(pdfDoc_) {
  pdfDoc = pdfDoc_;
  document.getElementById('page_count').textContent = pdfDoc.numPages;

  // Initial/first page rendering
  renderPage(pageNum);
});
</script>
{% endblock %}
</html>

keep_playing/sheetreader/templates/sheetreader/sheet_form.html
{% extends "sheetreader/base.html" %}
{% load static %}
<DOCTYPE html>
<html>
{% block content %}
	<head>
		<style type="text/css">
			.errorlist{
				margin-top: 48px;
			}
			label{
				margin-top: 10px;
				font-weight: bold;

			}
			.submit_button {
				background-color: #557a95;
				display: block; 
				margin-top: 20px; 
				margin-left: auto; 
				margin-right: auto;
			}
		</style>
	</head>
	<body>

		<div class="container"> 
			<h1 style="text-align: center; margin-top: 20px;"> Sheet Form </h1>
			<form method="POST" enctype="multipart/form-data" style="margin-top: 40px;">
				{% csrf_token %}					

				
						
						<strong><label for="id_sheet_name"> Sheet Name </label></strong>
						{{form.sheet_name}}
			
	
						<strong><label for="id_sheet_file"> Upload Sheet PDF Here </label></strong>
						{{form.sheet_file}}
			
						
		
					
						<button type="submit" class="btn btn-primary submit_button"> Submit </button>
				
			</form>
		</div>	

		<script type="text/javascript">			
			$("input").addClass("form-control")
			$("select").addClass("form-control")
		</script>
	</body>
{% endblock %}
</html>